#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/e5cfa8ff-74e9-4bcf-bacc-639dd653aba6 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  bool switch_led;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/


#include "thingProperties.h"

void setup() {
  Serial.begin(9600);
  delay(1500);

  pinMode(4, OUTPUT);
  digitalWrite(4, LOW);

  initProperties();

  ArduinoCloud.begin(ArduinoIoTPreferredConnection);

  setDebugMessageLevel(4);
  configTime(0, 0, "pool.ntp.org");
  ArduinoCloud.printDebugInfo();
}

void onSwitchLedChange() {
  digitalWrite(4, switch_led ? HIGH : LOW);
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  
  
}