#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/e5cfa8ff-74e9-4bcf-bacc-639dd653aba6 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  float distance;
  bool switch_led;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/


#include "thingProperties.h"

#define TRIG_PIN 5
#define ECHO_PIN 27
#define LED_PIN 4

void setup() {
  Serial.begin(9600);
  delay(1500);

  pinMode(TRIG_PIN, OUTPUT);
  pinMode(ECHO_PIN, INPUT);
  pinMode(LED_PIN, OUTPUT);
  digitalWrite(LED_PIN, LOW);

  initProperties();

  ArduinoCloud.begin(ArduinoIoTPreferredConnection);

  setDebugMessageLevel(2);
  configTime(0, 0, "pool.ntp.org");
  ArduinoCloud.printDebugInfo();
}

float readDistance() {
  digitalWrite(TRIG_PIN, LOW);
  delayMicroseconds(2);

  digitalWrite(TRIG_PIN, HIGH);
  delayMicroseconds(10);
  digitalWrite(TRIG_PIN, LOW);

  long duration = pulseIn(ECHO_PIN, HIGH);

  float distance = duration * 0.0343 / 2;
  return distance;
}


void onSwitchLedChange() {
  //digitalWrite(4, switch_led ? HIGH : LOW);
}

void loop() {
  ArduinoCloud.update();

  distance = readDistance();

  Serial.print("Distance: ");
  Serial.print(distance);
  Serial.println(" cm");

  if (distance > 0 && distance <= 5) {
    digitalWrite(LED_PIN, HIGH);
    switch_led = true;
    
  } else {
    digitalWrite(LED_PIN, LOW);
    switch_led = false;
  }

  delay(200);
  
  
}


