#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/e5cfa8ff-74e9-4bcf-bacc-639dd653aba6 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  float g_distance;
  float g_humidity;
  float g_temp;
  bool switch_led;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/


#include "thingProperties.h"
#include <DHT.h>
#include <BLEDevice.h>
#include <BLEServer.h>
#include <BLEUtils.h>
#include <BLE2902.h>

BLECharacteristic *pCharacteristic;

#define TRIG_PIN 5
#define ECHO_PIN 27
#define LED_PIN 4

#define DHT_PIN 2
#define DHT_TYPE DHT22

DHT dht(DHT_PIN, DHT_TYPE);

//=======================
//        SETUP
//=======================

void setup() {
  Serial.begin(9600);
  delay(1500);

  pinMode(TRIG_PIN, OUTPUT);
  pinMode(ECHO_PIN, INPUT);
  pinMode(LED_PIN, OUTPUT);
  digitalWrite(LED_PIN, LOW);

  initProperties();

  ArduinoCloud.begin(ArduinoIoTPreferredConnection);

  BLEDevice::init("ESP32");

  BLEServer *pServer = BLEDevice::createServer();
  BLEService *pService = pServer->createService("1234");
  
  pCharacteristic = pService->createCharacteristic(
    "5678",
    BLECharacteristic::PROPERTY_READ | BLECharacteristic::PROPERTY_NOTIFY
  );
  
  pCharacteristic->addDescriptor(new BLE2902());
  
  pService->start();
  BLEAdvertising *pAdvertising = BLEDevice::getAdvertising();
  pAdvertising->start();

  dht.begin();
  
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
  
  xTaskCreate(  sensorTask,  "SENS",  2048,  NULL,  1, NULL);
  xTaskCreate(  bleTask,  "BLE",  4096,  NULL,  1,  NULL);
  xTaskCreate(  displayTask,  "DISP",  2048,  NULL,  2,  NULL);
}
//=======================
//  Reading functions
//=======================

float readDistance() {
  digitalWrite(TRIG_PIN, LOW);
  delayMicroseconds(2);

  digitalWrite(TRIG_PIN, HIGH);
  delayMicroseconds(10);
  digitalWrite(TRIG_PIN, LOW);

  long duration = pulseIn(ECHO_PIN, HIGH, 30000);
  float distance = duration * 0.0343 / 2;
  return distance;
}
float readTemperature()
{
  float temp = dht.readTemperature();

  if (isnan(temp))
  {
    Serial.println("Failed to read temperature");
    return g_temp; 
  }

  return temp;
}
float readHumidity()
{
  float hum = dht.readHumidity();

  if (isnan(hum))
  {
    Serial.println("Failed to read humidity");
    return g_humidity; 
  }

  return hum;
}

//=======================
//        TASKS
//=======================

void sensorTask(void *pvParameters)
{
  while (true)
  {
    g_distance = readDistance();
    g_temp = readTemperature();
    g_humidity = readHumidity();

    vTaskDelay(pdMS_TO_TICKS(2000));
  }
}
void displayTask(void *pvParameters)
{
  while (true)
  {
    Serial.print("Distance: ");
    Serial.print(g_distance);

    Serial.print(" Temp: ");
    Serial.print(g_temp);

    Serial.print(" Hum: ");
    Serial.println(g_humidity);

    if (g_distance > 0 && g_distance <= 5)
    {
      digitalWrite(LED_PIN, HIGH);
      switch_led = true;
    }
    else
    {
      digitalWrite(LED_PIN, LOW);
      switch_led = false;
    }

    vTaskDelay(pdMS_TO_TICKS(500));
  }
}
void bleTask(void *pvParameters)
{
  while (true)
  {
    char data[80];
snprintf(data, sizeof(data),
"{T:%.1f,H:%.1f,D:%.1f}",
g_temp, g_humidity, g_distance);

    pCharacteristic->setValue(data);
    pCharacteristic->notify();

    vTaskDelay(pdMS_TO_TICKS(2000));
  }
}


void onSwitchLedChange() {
  //digitalWrite(4, switch_led ? HIGH : LOW);
}

void loop() {
  ArduinoCloud.update();
}
