#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "PlantMonitor"
  https://create.arduino.cc/cloud/things/ae3516b3-c13b-4fb9-9f87-24bd2493e215 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  float humidity;
  float temperature;
  int moisture;
  bool alertActive;
  bool wifiStatus;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
#include "DHTesp.h"
#include <BLEDevice.h>
#include <BLEServer.h>
#include <BLEUtils.h>
#include <BLE2902.h>

BLEServer* pServer;
BLEService* pService;
BLECharacteristic* pCharacteristic;

#define SERVICE_UUID        "12345678-1234-1234-1234-123456789abc"
#define CHARACTERISTIC_UUID "87654321-4321-4321-4321-cba987654321"

DHTesp dht;

const int DHT_PIN = 4;
const int POT_PIN = 3;

const int GREEN_LED = 2;
const int RED_LED = 5;

// -- Shared sensor globals --
volatile float  g_temperature = 0.0;   // DHT22 temperature (Celsius)
volatile float  g_humidity    = 0.0;   // DHT22 humidity (%)
volatile int    g_moisture    = 0;     // Potentiometer ADC (0-100%)
volatile bool   g_wifi_ok     = false; // WiFi/Cloud connection status
volatile bool   g_alert       = false; // Alert condition flag


void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  pinMode(GREEN_LED, OUTPUT);
  pinMode(RED_LED, OUTPUT);
  
  dht.setup(DHT_PIN, DHTesp::DHT22);
  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);

  //BLE SETUP
  BLEDevice::init("PlantMonitor");

  pServer = BLEDevice::createServer();
  
  pService = pServer->createService(SERVICE_UUID);
  
  pCharacteristic =
    pService->createCharacteristic(
      CHARACTERISTIC_UUID,
      BLECharacteristic::PROPERTY_READ |
      BLECharacteristic::PROPERTY_NOTIFY
    );
  
  pCharacteristic->addDescriptor(new BLE2902());
  
  pService->start();
  
  BLEAdvertising* advertising = BLEDevice::getAdvertising();
  
  advertising->addServiceUUID(SERVICE_UUID);
  
  advertising->start();
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
  
   xTaskCreate(sensorTask,
              "SENS",
              2048,
              NULL,
              1,
              NULL);

  xTaskCreate(cloudTask,
              "CLOUD",
              8192,
              NULL,
              1,
              NULL);

  xTaskCreate(bleTask,
              "BLE",
              4096,
              NULL,
              1,
              NULL);

  xTaskCreate(alertTask,
              "ALERT",
              2048,
              NULL,
              2,
              NULL);

  xTaskCreate(displayTask,
              "DISPLAY",
              2048,
              NULL,
              3,
              NULL);
}


// ---------------- SENSOR TASK ----------------
void sensorTask(void *p) {
  while (true) {

    TempAndHumidity data = dht.getTempAndHumidity();

    if (!isnan(data.temperature)) {
      g_temperature = data.temperature;
      g_humidity = data.humidity;
    }

    int raw = analogRead(POT_PIN);

    g_moisture = map(raw, 0, 4095, 0, 100);

    vTaskDelay(pdMS_TO_TICKS(2000));
  }
}

// ---------------- ALERT TASK ----------------
void alertTask(void *p) {

  bool blinkState = false;

  while (true) {

   if (WiFi.status() == WL_CONNECTED) {
      g_wifi_ok = true;
      digitalWrite(GREEN_LED, HIGH);
    }
    else {
      g_wifi_ok = false;
      digitalWrite(GREEN_LED, LOW);
    }


    if (g_temperature > 30) {

      g_alertActive = true;

      digitalWrite(RED_LED, HIGH);

      Serial.println("TEMP WARNING");
    }
    else if (g_moisture < 20) {

      g_alertActive = true;

      blinkState = !blinkState;

      digitalWrite(RED_LED, blinkState);

      Serial.println("WATER PLANT");
    }
    else {

      g_alertActive = false;

      digitalWrite(RED_LED, LOW);

      Serial.println("SYSTEM OK");
    }

    vTaskDelay(pdMS_TO_TICKS(500));
  }
}

// ---------------- DISPLAY TASK ----------------
void displayTask(void *p) {

  while (true) {

    Serial.println("======================================");
    Serial.printf("Temperature : %.1f C\n", g_temperature);
    Serial.printf("Humidity    : %.1f %%\n", g_humidity);
    Serial.printf("Moisture    : %d %%\n", g_moisture);
    Serial.printf("WiFi        : %s\n",
                  g_wifi_ok ? "Connected" : "Disconnected");
    Serial.printf("Alert       : %s\n",
                  g_alertActive ? "YES" : "NO");
    Serial.println("======================================");

    vTaskDelay(pdMS_TO_TICKS(1000));
  }
}

// ---------------- BLE TASK (Stub) ----------------
void bleTask(void *p) {

  while (true) {

    String sensorData =
      "{\"temp\":" + String(g_temperature, 1) +
      ",\"hum\":" + String(g_humidity, 1) +
      ",\"soil\":" + String(g_moisture) +
      ",\"wifi\":" + String(g_wifi_ok ? 1 : 0) +
      ",\"alert\":" + String(g_alert ? 1 : 0) +
      "}";

    pCharacteristic->setValue(sensorData.c_str());

    pCharacteristic->notify();

    Serial.print("BLE -> ");
    Serial.println(sensorData);

    vTaskDelay(pdMS_TO_TICKS(2000));
  }
}
// ---------------- CLOUD TASK ----------------
void cloudTask(void *p) {

  while (true) {

    temperature = g_temperature;

    humidity = g_humidity;

    soilMoisture = g_moisture;

    wifiStatus = g_wifi_ok;

    alertActive = g_alert;

    ArduinoCloud.update();

    vTaskDelay(pdMS_TO_TICKS(5000));
  }
}

void loop() {
  ArduinoCloud.update();
  delay(100);
}

/*
  Since GAlertActive is READ_WRITE variable, onGAlertActiveChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onGAlertActiveChange()  {
  // Add your code here to act upon GAlertActive change
}

/*
  Since GWifiStatus is READ_WRITE variable, onGWifiStatusChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onGWifiStatusChange()  {
  // Add your code here to act upon GWifiStatus change
}

/*
  Since AlertActive is READ_WRITE variable, onAlertActiveChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onAlertActiveChange()  {
  // Add your code here to act upon AlertActive change
}




/*
  Since WifiStatus is READ_WRITE variable, onWifiStatusChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onWifiStatusChange()  {
  // Add your code here to act upon WifiStatus change
}