// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "146346c2-4c06-40e7-a007-dec519a68e92";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onAlertActiveChange();
void onWifiStatusChange();

float humidity;
float temperature;
int moisture;
bool alertActive;
bool wifiStatus;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(humidity, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(temperature, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(moisture, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(alertActive, READWRITE, ON_CHANGE, onAlertActiveChange);
  ArduinoCloud.addProperty(wifiStatus, READWRITE, ON_CHANGE, onWifiStatusChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
